# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/uni/DAS/projects/lab11VGAgrey/lab11VGAgrey.srcs/sources_1/ip/frameBuffer/frameBuffer.xci
# IP: The module: 'frameBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/uni/DAS/projects/lab11VGAgrey/lab11VGAgrey.gen/sources_1/ip/frameBuffer/frameBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frameBuffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/uni/DAS/projects/lab11VGAgrey/lab11VGAgrey.srcs/sources_1/ip/frameBuffer/frameBuffer.xci
# IP: The module: 'frameBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/uni/DAS/projects/lab11VGAgrey/lab11VGAgrey.gen/sources_1/ip/frameBuffer/frameBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'frameBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
