# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: U:/hlocal/temp/DAS/sources/lab11VGAgrey/lab11VGAgrey.xdc

# IP: ip/frameBuffer/frameBuffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==frameBuffer || ORIG_REF_NAME==frameBuffer} -quiet] -quiet

# IP: ip/multAdd/multAdd.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multAdd || ORIG_REF_NAME==multAdd} -quiet] -quiet
